import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useState, useEffect } from "react";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import { WavyBackground } from "@/Components/ui/wavy-background";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Music Courses App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark">
			<body className={`${inter.className}`}>
				{" "}
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
